participants:
  - el_type: erigon
    el_image: racytech/erigon:latest
    cl_type: lighthouse
    count: 1
  - el_type: nethermind
    el_image: racytech/nethermind:latest
    cl_type: lighthouse
    count: 1
network_params:
  genesis_delay: 0
  electra_fork_epoch: 1
additional_services:
  - assertoor
  # - tx_spammer
assertoor_params:
  run_transaction_test: true
  run_blob_transaction_test: true
# tx_spammer_params:
#   tx_spammer_extra_args: []