# participants:
#   - el_type: erigon
#     el_image: racytech/erigon:latest
#     cl_type: lighthouse
#     count: 1
#   - el_type: nethermind
#     el_image: racytech/nethermind:latest
#     cl_type: lighthouse
#     count: 1
# network_params:
#   genesis_delay: 0
#   electra_fork_epoch: 1
# additional_services:
#   - assertoor
#   # - tx_spammer
# assertoor_params:
#   run_transaction_test: true
#   run_blob_transaction_test: true
# # tx_spammer_params:
# #   tx_spammer_extra_args: []


participants:
  - el_type: erigon
    el_image: racytech/erigon:eof-devnet-0
    cl_type: prysm
    cl_image: ethpandaops/prysm-beacon-chain:develop-557c5be
  - el_type: nethermind
    el_image: ethpandaops/nethermind:feature-evm-eof
    cl_type: prysm
    cl_image: ethpandaops/prysm-beacon-chain:develop-557c5be
  - el_type: reth
    el_image: ethpandaops/reth:main
    cl_type: prysm
    cl_image: ethpandaops/prysm-beacon-chain:develop-557c5be
  - el_type: besu
    el_image: ethpandaops/besu:main
    cl_type: prysm
    cl_image: ethpandaops/prysm-beacon-chain:develop-557c5be
global_log_level: info
network_params:
  electra_fork_epoch: 1
  fulu_fork_epoch: 2
  seconds_per_slot: 4
additional_services:
  - dora
snooper_enabled: true